jobs:
  build:
    permissions:
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Maven version
      run: 'mkdir -p ./.mvn

        echo ''-e -B -DtrimStackTrace=false'' > ./.mvn/maven.config

        mvn --version

        mkdir -p target

        '
    - continue-on-error: true
      name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
    - continue-on-error: true
      name: Maven build
      run: 'mvn install site

        '
    - continue-on-error: true
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GH }}
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/website')
        || startsWith(github.ref, 'refs/tags/v'))
      name: Website
      run: 'chmod +x ./.github/website.sh

        .github/website.sh

        '
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
